/*
  The shared UI kit: a progress bar and a dashboard shell.

  Eight tool pages run a request that takes between two seconds and two
  minutes. Until now every one of them did the same thing — disable the
  button, print a sentence, and leave the visitor staring at it. On the
  slower tools that reads as a page that has died.

  ── on making progress honest ──

  A progress bar that invents its own percentage is the same class of lie as
  a green "online" dot on a page where nothing runs. So this one is driven by
  real stages, and the rules are:

    · the label always names what is actually happening;
    · a stage only advances when the code actually reaches it;
    · inside a long stage the bar eases toward that stage's ceiling and
      stops there — it cannot wander into the next stage's band;
    · 100% happens on the real response and at no other time.

  The easing inside a stage is an estimate and is meant to be: it says "still
  working", which is true, and it never claims a step is finished before it
  is. What it must never do is sit at 99% for a minute, which is why each
  stage has its own ceiling rather than the whole bar having one.
*/

export const UI_START = "<!-- ui:start — generated by scripts/build-ui.mjs, do not edit by hand -->";
export const UI_END = "<!-- ui:end -->";

export function kitStyles() {
  return `
  /* ══ progress ═════════════════════════════════════════════════ */
  .prog {
    display: none; margin: 1.1rem 0 0;
    font-family: var(--sans, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif);
  }
  .prog[data-state="run"], .prog[data-state="done"], .prog[data-state="fail"] { display: block; }

  .prog-top {
    display: flex; align-items: baseline; justify-content: space-between;
    gap: 1rem; margin-bottom: .5rem;
  }
  .prog-step {
    font-size: .82rem; color: var(--ink-dim, #a09d93); font-weight: 300;
    display: flex; align-items: center; gap: .5rem; min-width: 0;
  }
  .prog-step span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  /* the dot pulses only while something is actually in flight */
  .prog-step::before {
    content: ""; width: 5px; height: 5px; border-radius: 50%; flex: none;
    background: var(--accent, #d4af6a);
  }
  .prog[data-state="run"] .prog-step::before { animation: prog-pulse 1.4s ease-in-out infinite; }
  .prog[data-state="done"] .prog-step::before { background: var(--go, #a8b878); animation: none; }
  .prog[data-state="fail"] .prog-step::before { background: var(--stop, #d98b6a); animation: none; }
  @keyframes prog-pulse { 0%, 100% { opacity: 1; } 50% { opacity: .25; } }

  .prog-pct {
    font-size: .8rem; color: var(--ink-faint, #6b6960);
    font-variant-numeric: tabular-nums; flex: none;
  }
  /* tabular figures, or the number jitters the label every tick */
  .prog-pct b {
    font-weight: 500; font-size: 1.05rem; color: var(--ink, #e8e6df);
    font-variant-numeric: tabular-nums;
  }
  .prog[data-state="done"] .prog-pct b { color: var(--go, #a8b878); }
  .prog[data-state="fail"] .prog-pct b { color: var(--stop, #d98b6a); }

  .prog-track {
    height: 3px; border-radius: 3px; overflow: hidden;
    background: var(--hairline, rgba(232, 230, 223, 0.12));
  }
  .prog-fill {
    height: 100%; width: 0%; border-radius: 3px;
    background: linear-gradient(90deg,
      color-mix(in srgb, var(--accent, #d4af6a) 55%, transparent),
      var(--accent, #d4af6a));
    transition: width .55s cubic-bezier(.22, 1, .36, 1), background .35s ease;
    position: relative;
  }
  @supports not (color: color-mix(in srgb, red 50%, blue)) {
    .prog-fill { background: var(--accent, #d4af6a); }
  }
  .prog[data-state="run"] .prog-fill::after {
    content: ""; position: absolute; inset: 0;
    background: linear-gradient(90deg, transparent, rgba(255,255,255,.28), transparent);
    animation: prog-sheen 1.6s ease-in-out infinite;
  }
  @keyframes prog-sheen { from { transform: translateX(-100%); } to { transform: translateX(100%); } }
  .prog[data-state="done"] .prog-fill { background: var(--go, #a8b878); }
  .prog[data-state="fail"] .prog-fill { background: var(--stop, #d98b6a); }

  @media (prefers-reduced-motion: reduce) {
    .prog-fill { transition: none; }
    .prog[data-state="run"] .prog-fill::after,
    .prog[data-state="run"] .prog-step::before { animation: none; }
  }
  @media print { .prog { display: none !important; } }

  /* ══ dashboard shell ══════════════════════════════════════════
     One layout language for every tool's results, so a visitor who has
     read one report can read all of them. */

  .dash { margin-top: 1.6rem; }

  .dash-head {
    display: flex; align-items: flex-end; justify-content: space-between;
    gap: 1.2rem; flex-wrap: wrap;
    padding-bottom: .9rem; margin-bottom: 1.3rem;
    border-bottom: 1px solid var(--hairline, rgba(232, 230, 223, 0.12));
  }
  .dash-head h2, .dash-head h3 { margin: 0; line-height: 1.2; }
  .dash-title .eyebrow {
    display: block; font-size: .68rem; letter-spacing: .14em; text-transform: uppercase;
    color: var(--ink-faint, #6b6960); margin-bottom: .3rem; font-weight: 400;
  }
  .dash-actions { display: flex; gap: .5rem; flex-wrap: wrap; }

  /* ── stat tiles: the answer before the detail ── */
  .dash-stats {
    display: grid; gap: .8rem; margin-bottom: 1.4rem;
    grid-template-columns: repeat(auto-fit, minmax(9.5rem, 1fr));
  }
  .dash-stat {
    padding: .85rem .95rem; border-radius: 4px;
    border: 1px solid var(--hairline, rgba(232, 230, 223, 0.12));
    background: rgba(232, 230, 223, 0.025);
  }
  .dash-stat .n {
    display: block; font-size: 1.5rem; line-height: 1.1; font-weight: 300;
    color: var(--ink, #e8e6df); font-variant-numeric: tabular-nums;
    font-family: var(--serif, Georgia, serif);
  }
  .dash-stat .l {
    display: block; margin-top: .3rem; font-size: .72rem;
    color: var(--ink-faint, #6b6960); line-height: 1.35;
  }
  /* An optional second line. The workflow planner's figures carried three
     pieces — value, label and a qualifier like "per month · 109h a year" —
     and a shared tile that could only hold two would have thrown the
     qualifier away to gain consistency. That is a bad trade. */
  .dash-stat .s {
    display: block; margin-top: .35rem; font-size: .68rem; line-height: 1.4;
    color: var(--ink-faint, #6b6960); opacity: .85;
  }
  /* A tile that spans the row, for a note that belongs with the figures
     rather than under them. */
  .dash-stat--wide { grid-column: 1 / -1; }
  .dash-stat--wide .l { margin-top: 0; }
  .dash-stat[data-tone="good"] .n { color: var(--go, #a8b878); }
  .dash-stat[data-tone="warn"] .n { color: var(--warn, #d4af6a); }
  .dash-stat[data-tone="bad"]  .n { color: var(--stop, #d98b6a); }
  .dash-stat[data-tone="accent"] .n { color: var(--accent, #d4af6a); }

  /* ── panels: one idea per box, titled ── */
  .dash-panel {
    border: 1px solid var(--hairline, rgba(232, 230, 223, 0.12));
    border-radius: 4px; padding: 1.1rem 1.15rem; margin-bottom: 1rem;
    background: rgba(232, 230, 223, 0.015);
  }
  .dash-panel > h3, .dash-panel > h4 {
    margin: 0 0 .2rem; font-size: .95rem; font-weight: 400;
    font-family: var(--serif, Georgia, serif);
  }
  .dash-panel > .hint {
    margin: 0 0 .9rem; font-size: .76rem; color: var(--ink-faint, #6b6960);
  }
  .dash-panel.is-warn { border-left: 2px solid var(--warn, #d4af6a); }
  .dash-panel.is-bad  { border-left: 2px solid var(--stop, #d98b6a); }

  .dash-cols { display: grid; gap: 1rem; grid-template-columns: 1fr 1fr; }
  @media (max-width: 46rem) { .dash-cols { grid-template-columns: 1fr; } }

  /* Wide content scrolls inside its own box; the page never scrolls sideways. */
  .dash-scroll { overflow-x: auto; -webkit-overflow-scrolling: touch; }

  @media print {
    .dash-panel { break-inside: avoid; border-color: #ccc; background: none; }
    .dash-stat { break-inside: avoid; }
  }
`;
}

export function kitScript() {
  return `
/*
  CMProgress — a staged progress bar.

  attach(mountSelector, steps) where each step is {label, w, slow}:
    w     relative width of the step's band (default 1)
    slow  the step eases toward its ceiling while it waits

  begin() enters step 0, next() advances, done()/fail() end it.
*/
window.CMProgress = (function () {
  function attach(mount, steps) {
    var host = typeof mount === "string" ? document.querySelector(mount) : mount;
    if (!host) return noop();

    /*
      Stop whatever was running here before.

      Two runs can overlap — a second submit while the first is still in
      flight, or the website builder's Rebuild button, which calls the same
      function again. Without this, the previous controller's interval keeps
      painting into the same element, and you get the older run's percentage
      fighting the newer run's label: a bar that reads "done" at 71%.

      Found by accident, by submitting twice. The disabled button makes it
      rare rather than impossible, and "rare" is not a fix.
    */
    if (host.__cmStop) { try { host.__cmStop(); } catch (e) {} }

    host.innerHTML =
      '<div class="prog-top">' +
        '<span class="prog-step"><span></span></span>' +
        '<span class="prog-pct"><b>0</b>%</span>' +
      '</div>' +
      '<div class="prog-track"><div class="prog-fill"></div></div>';
    host.className = "prog";
    host.setAttribute("role", "status");
    host.setAttribute("aria-live", "polite");

    var label = host.querySelector(".prog-step span");
    var pct = host.querySelector(".prog-pct b");
    var fill = host.querySelector(".prog-fill");

    var total = steps.reduce(function (a, s) { return a + (s.w || 1); }, 0);
    var bands = [], acc = 0;
    steps.forEach(function (s) {
      var from = acc / total, to = (acc + (s.w || 1)) / total;
      bands.push({ from: from, to: to, step: s });
      acc += s.w || 1;
    });

    var i = -1, timer = null, enteredAt = 0, shown = 0, dead = false;

    // Registered so the next attach() on this element can shut this one down.
    host.__cmStop = function () { dead = true; clearInterval(timer); };

    function paint(p) {
      if (dead) return;                      // superseded by a later run
      shown = Math.max(shown, p);            // never runs backwards
      fill.style.width = (shown * 100).toFixed(1) + "%";
      pct.textContent = Math.round(shown * 100);
    }

    function tick() {
      var b = bands[i];
      if (!b) return;
      var elapsed = (Date.now() - enteredAt) / 1000;
      /* Asymptotic: fast at first, then slower, never reaching the ceiling.
         tau is a guess at how long the step takes; being wrong changes the
         pace, not the honesty — the bar still stops at this step's band. */
      var tau = b.step.tau || 12;
      var eased = 1 - Math.exp(-elapsed / tau);
      paint(b.from + (b.to - b.from) * eased * 0.97);
    }

    function enter(n) {
      if (dead) return;
      i = n;
      var b = bands[i];
      if (!b) return;
      enteredAt = Date.now();
      label.textContent = b.step.label;
      host.dataset.state = "run";
      paint(b.from);
      clearInterval(timer);
      if (b.step.slow) timer = setInterval(tick, 220);
    }

    return {
      begin: function () { shown = 0; host.dataset.state = "run"; enter(0); return this; },
      next: function () { clearInterval(timer); if (i + 1 < bands.length) enter(i + 1); return this; },
      to: function (n) { clearInterval(timer); enter(Math.min(n, bands.length - 1)); return this; },
      /* The only place 100% is written. */
      done: function (msg) {
        clearInterval(timer);
        if (dead) return this;
        host.dataset.state = "done";
        label.textContent = msg || "Done";
        shown = 1; fill.style.width = "100%"; pct.textContent = "100";
        return this;
      },
      fail: function (msg) {
        clearInterval(timer);
        if (dead) return this;
        host.dataset.state = "fail";
        label.textContent = msg || "That did not work";
        return this;
      },
      reset: function () {
        clearInterval(timer);
        if (dead) return this;
        host.dataset.state = "idle";
        shown = 0; fill.style.width = "0%"; pct.textContent = "0";
        return this;
      },
    };
  }

  function noop() {
    var self = { begin: f, next: f, to: f, done: f, fail: f, reset: f };
    function f() { return self; }
    return self;
  }

  return { attach: attach };
})();
`;
}
