import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import {
  assemble, ensureDir, explodeFrames, firstFrame, gateJunction, lastFrame,
} from "./junction.mjs";
import { generateClip, generateKeyframe, uploadMedia } from "../media/higgsfield.mjs";
import { renderFilmPage } from "./page.mjs";

/*
  The chain: a storyboard in, one continuous film out.

  ── the shape of it ──

    keyframe ──▶ clip 1 ──▶ last frame ──▶ clip 2 ──▶ last frame ──▶ clip 3
                    │                         │                        │
                  gate                      gate                     gate

  Every clip after the first is generated FROM the previous clip's last frame,
  and every seam is measured rather than trusted. That is what makes it one
  shot instead of three clips with dissolves over the joins.

  ── cost discipline ──

  Generation is the only expensive thing here and it is spent before anyone
  has seen the result, so:

    · the whole chain is drafted at the cheap tier and the cheap resolution
      first, so a storyboard that does not work costs pennies to find out;
    · the total is quoted before a single call is made, never after;
    · a failed junction is regenerated once, not silently accepted, and not
      retried forever.

  Mastering at full resolution is a separate pass over prompts that have
  already been approved.
*/

/**
 * What a chain will generate. Not what it costs.
 *
 * This used to price another engine's credits. Higgsfield bills in its own currency at
 * its own rates, and a number invented here would look authoritative and be
 * wrong — so this reports the shape of the run and the CLI is asked for the
 * money.
 */
export function quoteChain({ chapters, seconds = 5 }) {
  return {
    clips: chapters.length,
    keyframes: chapters.length + 1,
    seconds,
    totalSeconds: chapters.length * seconds,
  };
}

/**
 * Turns a chapter into a shot instruction.
 *
 * The camera direction is explicit and continuous — "continue the same
 * unbroken take" — because the model is being handed the previous frame and
 * asked to carry on, not to start something new. Prompts that describe a
 * scene rather than a continuation are what produce a cut.
 */
export function shotPrompt(chapter, index) {
  const opening = index === 0
    ? "Open on"
    : "Continue the same unbroken take, moving on from exactly this frame:";
  return [
    opening,
    chapter.visual,
    "Slow, deliberate camera movement. Cinematic, no cuts, no titles, no text on screen.",
  ].join(" ");
}

/**
 * Builds the whole film.
 *
 * onStep is called with plain progress so a CLI can narrate it; nothing here
 * prints, because a library that writes to stdout cannot be used twice.
 */
export async function buildFilm({
  spec,
  outDir,
  seconds = 5,
  tier = "cheap",
  resolution = "480p",
  frames = 240,
  references = [],
  soulId = null,
  onStep = () => {},
}) {
  const chapters = spec.chapters ?? [];
  if (!chapters.length) throw new Error("The spec has no chapters to film");

  const clipsDir = await ensureDir(join(outDir, "clips"));
  const workDir = await ensureDir(join(outDir, "work"));

  const quote = quoteChain({ chapters, seconds, tier });
  onStep({ step: "quote", ...quote });

  /*
    Every boundary frame first.

    Seedance pins both ends of a clip, so a junction is only continuous if
    the frame on either side of it already exists and both neighbours were
    handed it. That means N+1 stills before any video: one to open on, one
    to close each chapter.

    All of them come from Soul 2.0 on the same account as the clips. A
    keyframe generated by a different model is a different world, and every
    clip that starts on it inherits the mismatch.
  */
  /*
    The client's own photographs, uploaded once.

    Every keyframe and every clip can be handed the same reference ids, so
    they are uploaded here rather than per generation — a dozen re-uploads of
    the same jpg is time nobody gets back.

    This is what turns a film of a generic bakery into a film of theirs, and
    it is the whole reason the Premium tier is worth what it costs.
  */
  const referenceIds = [];
  for (const [i, path] of references.entries()) {
    onStep({ step: "upload", index: i, of: references.length, path });
    referenceIds.push(await uploadMedia(path));
  }

  /*
    Boundary frames, generated and downloaded.

    Two things learned the expensive way and fixed before spending.

    The CLI takes an upload id or a local file path for a pin — a URL is
    rejected outright with "neither a UUID nor an existing file path". The
    keyframe generator returns URLs, so every frame is downloaded and the
    path is what gets passed. Without this the first clip fails after seven
    keyframes have already been paid for.

    ── why the keyframes are NOT chained ──

    Passing each frame as a reference for the next was tried and reverted.
    Soul 2.0 treats an image reference as a strong content anchor rather than
    a hint about the world, so every frame came back as a variation of the
    one before it: eight beautiful, near-identical empty rooms, and not one
    of the shots the storyboard actually asked for. It held the world and
    threw away the film.

    Without it the shots are correct and the world is carried by the prompt
    instead — which is why every chapter's visual states the same lamp, the
    same wood and the same palette. Faces still drift between independent
    generations, and no prompt fixes that; a storyboard that keeps faces out
    of all but one shot does.
  */
  const boundaries = [];

  for (let i = 0; i <= chapters.length; i++) {
    const chapter = chapters[Math.min(i, chapters.length - 1)];
    onStep({ step: "keyframe", index: i, of: chapters.length + 1, name: chapter.name });

    const frame = await generateKeyframe({
      /*
        The concept name is deliberately NOT in here.

        It was passed as mood and came back rendered: engraved on a razor the
        first time, and the second time as garbled neon across a whole Taipei
        lane, on a film whose concept name was 一杯的工夫. A title is a string
        of characters, and a model handed characters draws them — so the same
        prompt that forbids lettering was quietly supplying some. shotlist.mjs
        has stated this rule from the day it was written; this line was the
        one place that broke it.

        "One continuous frame" earns its place too: a shot describing more
        than one state came back as a diptych, two panels side by side in a
        single keyframe.
      */
      prompt: `${chapter.visual}. One continuous cinematic still, a single ` +
              `frame with no panels, no split screen, no before-and-after ` +
              `comparison. No text, no lettering, no signage, no titles, no watermark.`,
      // The client's own photographs still anchor the world when they gave
      // us any. What is deliberately absent is the previous keyframe.
      references: referenceIds,
      soulId,
    }, { onStep: (s2) => onStep({ ...s2, index: i }) });

    const local = join(workDir, `key-${String(i).padStart(2, "0")}.jpg`);
    await download(frame.url, local);
    boundaries.push(local);

  }

  const junctions = [];
  const clipFiles = [];
  let seedFile = null;

  for (const [i, chapter] of chapters.entries()) {
    onStep({ step: "clip", index: i, of: chapters.length, name: chapter.name });

    const clip = await generateClip({
      prompt: shotPrompt(chapter, i),
      startImage: boundaries[i],
      endImage: boundaries[i + 1],
      seconds,
      resolution,
      references: referenceIds,
    }, { onStep: (s2) => onStep({ ...s2, index: i, name: chapter.name }) });

    const localClip = join(clipsDir, `clip-${String(i).padStart(2, "0")}.mp4`);
    await download(clip.url, localClip);

    /* The gate still runs. Pinning is an instruction, not a guarantee, and a
       seam that was promised and not delivered is the thing worth catching. */
    if (seedFile) {
      const actual = join(workDir, `first-${i}.jpg`);
      await firstFrame(localClip, actual);
      const gate = await gateJunction({ seed: seedFile, actual });
      onStep({ step: "junction", index: i, ...gate });
      junctions.push({ index: i, name: chapter.name, ...gate });
    }

    seedFile = join(workDir, `last-${i}.jpg`);
    await lastFrame(localClip, seedFile);
    clipFiles.push(localClip);
  }

  onStep({ step: "assemble", clips: clipFiles.length });
  const film = join(outDir, "film.mp4");
  await assemble({ clips: clipFiles, out: film, workDir });

  onStep({ step: "frames", target: frames });
  const exploded = await explodeFrames({ video: film, dir: join(outDir, "frames"), count: frames });

  const manifest = {
    concept: spec.conceptName,
    chapters: chapters.map((c) => ({ name: c.name, visual: c.visual })),
    clips: clipFiles.length,
    seconds: exploded.seconds,
    frames: exploded.count,
    junctions,
    worstJunction: junctions.length ? Math.min(...junctions.map((j) => j.score)) : null,
    quote,
  };
  await writeFile(join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2));

  // The frames are only useful attached to something that scrubs them.
  await writeFile(join(outDir, "index.html"), renderFilmPage({ manifest, spec }));

  onStep({ step: "done", ...manifest });
  return manifest;
}

async function download(url, to) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Could not download ${url}: ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(to, buffer);
  return to;
}
